Repository pahud/aws-cdk-examples, pull requests merged in 2023-07, with the labels that each got.

#13 chore(deps): upgrade dependencies
  typescript/apigateway-patterns/package.json
Labels: auto-approve, auto-merge

#23 chore(deps): upgrade dependencies
  typescript/eks/.projen/tasks.json
  typescript/eks/package.json
Labels: auto-approve, auto-merge

#25 feat: support eks with k8s 1.27
  typescript/eks/.projen/deps.json
  typescript/eks/.projenrc.ts
  typescript/eks/package.json
  typescript/eks/src/main.ts
Labels: auto-approve, auto-merge

#24 chore(deps): upgrade dependencies
  typescript/apigateway-patterns/package.json
Labels: auto-approve, auto-merge

#26 chore(deps): upgrade dependencies
  typescript/ec2-instance-connect-endpoint/package.json
Labels: auto-approve, auto-merge

#29 eks: update snapshots
  .github/workflows/auro-merge.yml
  typescript/eks/.projenrc.ts
  typescript/eks/src/main.ts
  typescript/eks/src/util.ts
  typescript/eks/test/__snapshots__/main.test.ts.snap
  typescript/eks/test/main.test.ts
Labels: auto-approve, auto-merge, automerge

#30 chore(deps): upgrade dependencies
  typescript/eks/package.json
Labels: auto-approve, auto-merge

#28 chore(deps): upgrade dependencies
  typescript/apigateway-patterns/package.json
Labels: auto-approve, auto-merge, automerge

#31 chore(deps): upgrade dependencies
  typescript/ec2-instance-connect-endpoint/package.json
Labels: auto-approve, automerge

#32 feat(apigateway-patterns): support defaultDomainName
  typescript/apigateway-patterns/src/agw-balanced-fargate-service.ts
  typescript/apigateway-patterns/src/integ.default.ts
  typescript/apigateway-patterns/test/__snapshots__/integ.default.test.ts.snap
Labels: auto-approve, automerge

#33 chore(deps): upgrade dependencies
  typescript/lambda-custom-runtime/.projen/tasks.json
  typescript/lambda-custom-runtime/package.json
Labels: auto-approve, automerge

#34 chore: add yarn.lock
  typescript/lambda-custom-runtime/.gitignore
  typescript/lambda-custom-runtime/.npmignore
  typescript/lambda-custom-runtime/.projenrc.ts
  typescript/lambda-custom-runtime/yarn.lock
Labels: auto-approve, auto-merge, automerge

#35 chore: add yarn.lock
  typescript/ec2-instance-connect-endpoint/.gitignore
  typescript/ec2-instance-connect-endpoint/.npmignore
  typescript/ec2-instance-connect-endpoint/.projenrc.ts
  typescript/ec2-instance-connect-endpoint/yarn.lock
Labels: auto-approve, automerge

#36 chore: add yarn.lock
  typescript/apigateway-patterns/.gitignore
  typescript/apigateway-patterns/.npmignore
  typescript/apigateway-patterns/.projen/deps.json
  typescript/apigateway-patterns/.projen/tasks.json
  typescript/apigateway-patterns/.projenrc.ts
  typescript/apigateway-patterns/package.json
  typescript/apigateway-patterns/yarn.lock
Labels: auto-approve, automerge

#37 chore: add yarn.lock
  typescript/aws-imagebuilder/.github/workflows/pull-request-lint.yml
  typescript/aws-imagebuilder/.github/workflows/upgrade-main.yml
  typescript/aws-imagebuilder/.gitignore
  typescript/aws-imagebuilder/.npmignore
  typescript/aws-imagebuilder/.projen/deps.json
  typescript/aws-imagebuilder/.projen/tasks.json
  typescript/aws-imagebuilder/.projenrc.ts
  typescript/aws-imagebuilder/API.md
  typescript/aws-imagebuilder/package.json
  typescript/aws-imagebuilder/src/index.ts
  typescript/aws-imagebuilder/src/integ.default.ts
  typescript/aws-imagebuilder/test/__snapshots__/integ.pipeline.test.ts.snap
  typescript/aws-imagebuilder/yarn.lock
Labels: auto-approve, automerge

#38 chore(deps): upgrade dependencies
  typescript/lambda-custom-runtime/package.json
  typescript/lambda-custom-runtime/yarn.lock
Labels: auto-approve, automerge

#39 chore(deps): upgrade dependencies
  typescript/eks/package.json
Labels: auto-approve, automerge

#41 chore(deps): upgrade dependencies
  typescript/ec2-instance-connect-endpoint/package.json
  typescript/ec2-instance-connect-endpoint/yarn.lock
Labels: auto-approve, automerge

#40 chore(deps): upgrade dependencies
  typescript/apigateway-patterns/package.json
  typescript/apigateway-patterns/yarn.lock
Labels: auto-approve, automerge

#43 chore(eks): add README with minor update
  typescript/eks/README.md
  typescript/eks/src/main.ts
Labels: auto-approve, automerge

#44 chore(deps): upgrade dependencies
  typescript/eks/yarn.lock
Labels: auto-approve, automerge

#47 chore(deps): upgrade dependencies
  typescript/lambda-custom-runtime/yarn.lock
Labels: auto-approve, automerge

#45 chore(deps): upgrade dependencies
  typescript/ec2-instance-connect-endpoint/yarn.lock
Labels: auto-approve, automerge

#46 chore(deps): upgrade dependencies
  typescript/apigateway-patterns/yarn.lock
Labels: auto-approve, automerge

#50 chore(deps): upgrade dependencies
  typescript/eks/package.json
  typescript/eks/yarn.lock
Labels: auto-approve, automerge

#52 chore(deps): upgrade dependencies
  typescript/lambda-custom-runtime/package.json
  typescript/lambda-custom-runtime/yarn.lock
Labels: auto-approve, automerge

#49 chore(deps): upgrade dependencies
  typescript/ec2-instance-connect-endpoint/package.json
  typescript/ec2-instance-connect-endpoint/yarn.lock
Labels: auto-approve, automerge

#51 chore(deps): upgrade dependencies
  typescript/apigateway-patterns/package.json
  typescript/apigateway-patterns/yarn.lock
Labels: auto-approve, automerge

#53 chore(deps): upgrade dependencies
  typescript/eks/yarn.lock
Labels: auto-approve, automerge

#56 chore(deps): upgrade dependencies
  typescript/lambda-custom-runtime/yarn.lock
Labels: auto-approve, automerge

#54 chore(deps): upgrade dependencies
  typescript/ec2-instance-connect-endpoint/yarn.lock
Labels: auto-approve, automerge

#55 chore(deps): upgrade dependencies
  typescript/apigateway-patterns/yarn.lock
Labels: auto-approve, automerge

#57 chore(deps): upgrade dependencies
  typescript/eks/package.json
  typescript/eks/yarn.lock
Labels: auto-approve, automerge

#60 chore(deps): upgrade dependencies
  typescript/lambda-custom-runtime/package.json
  typescript/lambda-custom-runtime/yarn.lock
Labels: auto-approve, automerge

#58 chore(deps): upgrade dependencies
  typescript/ec2-instance-connect-endpoint/package.json
  typescript/ec2-instance-connect-endpoint/yarn.lock
Labels: auto-approve, automerge

#59 chore(deps): upgrade dependencies
  typescript/apigateway-patterns/package.json
  typescript/apigateway-patterns/yarn.lock
Labels: auto-approve, automerge

#61 chore(deps): upgrade dependencies
  typescript/eks/package.json
  typescript/eks/yarn.lock
Labels: auto-approve, automerge

#64 chore(deps): upgrade dependencies
  typescript/lambda-custom-runtime/package.json
  typescript/lambda-custom-runtime/yarn.lock
Labels: auto-approve, automerge

#63 chore(deps): upgrade dependencies
  typescript/apigateway-patterns/package.json
  typescript/apigateway-patterns/yarn.lock
Labels: auto-approve, automerge

#62 chore(deps): upgrade dependencies
  typescript/ec2-instance-connect-endpoint/package.json
  typescript/ec2-instance-connect-endpoint/yarn.lock
Labels: auto-approve, automerge

#67 chore: use awscdk-resources-mongodbatlas
  typescript/mongodb-atlas/.projen/deps.json
  typescript/mongodb-atlas/.projenrc.ts
  typescript/mongodb-atlas/API.md
  typescript/mongodb-atlas/package.json
  typescript/mongodb-atlas/src/bootstrap.ts
  typescript/mongodb-atlas/src/demo-stack.ts
  typescript/mongodb-atlas/src/integ.default.ts
  typescript/mongodb-atlas/test/__snapshots__/integ.default.test.ts.snap
  typescript/mongodb-atlas/yarn.lock
Labels: auto-approve, automerge

#68 chore(deps): upgrade dependencies
  typescript/mongodb-atlas/yarn.lock
Labels: auto-approve, automerge

#69 chore(deps): upgrade dependencies
  typescript/eks/package.json
  typescript/eks/yarn.lock
Labels: auto-approve, automerge

#72 chore(deps): upgrade dependencies
  typescript/lambda-custom-runtime/package.json
  typescript/lambda-custom-runtime/yarn.lock
Labels: auto-approve, automerge

#71 chore(deps): upgrade dependencies
  typescript/apigateway-patterns/package.json
  typescript/apigateway-patterns/yarn.lock
Labels: auto-approve, automerge

#70 chore(deps): upgrade dependencies
  typescript/ec2-instance-connect-endpoint/package.json
  typescript/ec2-instance-connect-endpoint/yarn.lock
Labels: auto-approve, automerge

#73 chore(deps): upgrade dependencies
  typescript/mongodb-atlas/package.json
  typescript/mongodb-atlas/yarn.lock
Labels: auto-approve, automerge

#74 chore(deps): upgrade dependencies
  typescript/eks/package.json
  typescript/eks/yarn.lock
Labels: auto-approve, automerge

#77 chore(deps): upgrade dependencies
  typescript/lambda-custom-runtime/package.json
  typescript/lambda-custom-runtime/yarn.lock
Labels: auto-approve, automerge

#75 chore(deps): upgrade dependencies
  typescript/ec2-instance-connect-endpoint/package.json
  typescript/ec2-instance-connect-endpoint/yarn.lock
Labels: auto-approve, automerge

#76 chore(deps): upgrade dependencies
  typescript/apigateway-patterns/package.json
  typescript/apigateway-patterns/yarn.lock
Labels: auto-approve, automerge

#78 chore: update README with diagrams for mongodb-atlas example
  typescript/mongodb-atlas/README.md
  typescript/mongodb-atlas/images/cluster.png
  typescript/mongodb-atlas/images/diagram.svg
  typescript/mongodb-atlas/src/integ.default.ts
  typescript/mongodb-atlas/test/integ.default.test.ts
Labels: auto-approve, automerge

#80 chore(deps): upgrade dependencies
  typescript/mongodb-atlas/package.json
  typescript/mongodb-atlas/yarn.lock
Labels: auto-approve, automerge

#81 chore(deps): upgrade dependencies
  typescript/eks/package.json
  typescript/eks/yarn.lock
Labels: auto-approve, automerge

#84 chore(deps): upgrade dependencies
  typescript/lambda-custom-runtime/package.json
  typescript/lambda-custom-runtime/yarn.lock
Labels: auto-approve, automerge

#82 chore(deps): upgrade dependencies
  typescript/ec2-instance-connect-endpoint/package.json
  typescript/ec2-instance-connect-endpoint/yarn.lock
Labels: auto-approve, automerge

#83 chore(deps): upgrade dependencies
  typescript/apigateway-patterns/package.json
  typescript/apigateway-patterns/yarn.lock
Labels: auto-approve, automerge

#85 feat(mongodb): support vpc peering
  typescript/mongodb-atlas/API.md
  typescript/mongodb-atlas/README.md
  typescript/mongodb-atlas/images/peering-diagram.svg
  typescript/mongodb-atlas/src/bootstrap.ts
  typescript/mongodb-atlas/src/demo-stack.ts
  typescript/mongodb-atlas/src/demo.ts
  typescript/mongodb-atlas/src/integ.default.ts
  typescript/mongodb-atlas/test/__snapshots__/integ.default.test.ts.snap
  typescript/mongodb-atlas/test/integ.default.test.ts
Labels: auto-approve, automerge

#86 feat(mongodb): add custom resource to accept vpc peering request
  typescript/mongodb-atlas/API.md
  typescript/mongodb-atlas/README.md
  typescript/mongodb-atlas/lambda/vpc-peering-handler.py
  typescript/mongodb-atlas/src/demo.ts
  typescript/mongodb-atlas/src/integ.default.ts
  typescript/mongodb-atlas/test/__snapshots__/integ.default.test.ts.snap
Labels: auto-approve, automerge

#87 chore(deps): upgrade dependencies
  typescript/aws-imagebuilder/.projen/tasks.json
  typescript/aws-imagebuilder/package.json
  typescript/aws-imagebuilder/yarn.lock
Labels: auto-approve, automerge
